/**
 * @file obfuscatedEncryptionIV.h
 *
 * The iv in this file is obfuscated by flipping the 7th bit of every other byte. The original iv is:5336eacc4b241f6a80f17bfcfba8deb1
 * Created on: 02:59PM on May 21, 2020
 * Generated by utility located at \drinkworks-freertos\utilities\encryptor\encryptor.py
 */
 
0xd3, 0x36, 0x6a, 0xcc, 0xcb, 0x24, 0x9f, 0x6a, 0x00, 0xf1, 0xfb, 0xfc, 0x7b, 0xa8, 0x5e, 0xb1
